### ISSUE TITLE
I got this error

### ISSUE THREAD

**Issue by zhangzq71** [Blazored/TextEditor#7]
[2020-02-04T03:02:25.615Z] Error: Microsoft.JSInterop.JSException: 'Quill' is not defined
ReferenceError: 'Quill' is not defined
   at window.QuillFunctions.createQuill (https://localhost:44327/_content/Blazored.TextEditor/Blazored-BlazorQuill.js:7:13)
   at Anonymous function (https://localhost:44327/_framework/blazor.server.js:8:31414)
   at Promise (native code)
   at e.jsCallDispatcher.beginInvokeJSFromDotNet (https://localhost:44327/_framework/blazor.server.js:8:31384)
   at Anonymous function (https://localhost:44327/_framework/blazor.server.js:1:19193)
   at Array.prototype.forEach (native code)
   at e.prototype.invokeClientMethod (https://localhost:44327/_framework/blazor.server.js:1:19171)
   at e.prototype.processIncomingData (https://localhost:44327/_framework/blazor.server.js:1:17160)
   at connection.onreceive (https://localhost:44327/_framework/blazor.server.js:1:10267)
   at i.onmessage (https://localhost:44327/_framework/blazor.server.js:1:37967)

   at Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation[T](String identifier, Object[] args)

   at Blazored.TextEditor.BlazoredTextEditor.OnAfterRenderAsync(Boolean firstRender) in D:\projects\WebApp\demo\TextEditor\src\Blazored.TextEditor\BlazoredTextEditor.razor:line 41

   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

**Comment by ADefWebserver** [comment]
We will need more information :) For example, pull down this project and run the sample at: https://github.com/Blazored/TextEditor/tree/master/samples/BlazorServerSide Doers that work for you?

**Comment by zhangzq71** [comment]
I was using the BlazorServerSide samle clone from git, it is 'commit a5700191a9269c98e27f98ee48e8577869dd0491'

**Comment by ADefWebserver** [comment]
I just pulled the [latest version of the project down](https://github.com/Blazored/TextEditor.git), opened it up in Visual Studio 2019 that was updated to the latest SDK and it ran fine.

**Comment by zhangzq71** [comment]
My SDK is Version:   3.1.101, Commit:    b377529961, visual studio is 'Version 16.4.4'.
I also tried https://github.com/ADefWebserver/Blazor-Blogs, got the same error.

**Comment by ADefWebserver** [comment]
In the project, it is trying to pull the **Quill JavaScript** from [https://cdn.quilljs.com/1.3.6/quill.js](https://cdn.quilljs.com/1.3.6/quill.js) - Can you get to the address? 

Another thing to try is to run: https://github.com/oqtane/oqtane.framework
That project has the quill.js inside the project. If that works, then the problem is you are unable to reach the quill.js file.

**Comment by zhangzq71** [comment]
Oh, you are right, there is sometimes it can't access https://cdn.quilljs.com/1.3.6/quill.js, I downloaded that js file and that css files from quilljs.com, it runs well, thank you very much!
